apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  labels:
    app: boardgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: sampath07/boardshack:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
      livenessProbe:
        httpGet:
          path: /actuator/health
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 10
        failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: boardgame-ssvc
  labels:
    app: boardgame
spec:
  type: NodePort   # ✅ Use NodePort for EC2-based clusters
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 80          # external service port
      targetPort: 8080  # matches containerPort
      nodePort: 30080   # accessible via EC2 public IP
